### ISSUE TITLE
"invalid multibyte char" when handling UTF-8 data in Ruby script

### ISSUE THREAD

**Issue by araidzuna** [twineworks/ruby-for-pentaho-kettle#16]
I have been really enjoying using the Ruby scripting step in Pentaho since finding it recently. However, I deal with a lot of Unicode data and I am running into issues trying to deal with UTF8 strings within the Ruby script step.

Whenever I try to manipulate or reference UTF8 text in the script I encounter a problem, which varies depending on the "Ruby Compatibility" configuration.

For example, simply trying to assign text to a field

``` ruby
$row["last"] = "文字化け"
```

results in either malformed garbage text (using 1.8 Compatibility) or an "invalid multibyte char (US-ASCII)" SyntaxError exception (using 1.9 Compatibility).

> 2012/11/07 15:09:54 - Ruby Scripting.0 - ERROR (version 4.3.0-stable, build 16786 from 2012-04-24 14.11.32 by buildguy) : Caused by: org.jruby.exceptions.RaiseException: (SyntaxError) Ruby Script:14: invalid multibyte char (US-ASCII)
> 2012/11/07 15:09:54 - Ruby Scripting.0 - ERROR (version 4.3.0-stable, build 16786 from 2012-04-24 14.11.32 by buildguy) : Error initializing step [Ruby Scripting]

I have tried a long list of the usual Ruby fixes to force UTF8 handling, including:

``` ruby
#!/bin/env ruby -wKu
# encoding: utf-8
$KCODE = "u"
Encoding.default_internal = "utf-8"
```

But these do not seem to be effective. When investigating the internal and external encoding states, Ruby seems to always be operating within "US-ASCII" regardless.

My apologies if I'm just missing something obvious with my configuration. I can't be sure whether or not this is a high-level problem within the Ruby scripting step itself or something deeper in the jRuby implementation or somewhere else, so I thought I would try asking here. Please let me know if I need to provide more detailed error logs or anything else.

 I would greatly appreciate any help on this matter. Thank you for your time!

**Comment by slawo-ch** [comment]
All code is now interpreted as UTF8 by default.
