### ISSUE TITLE
Memory usage with Java API

### ISSUE THREAD

**Issue by dbron0000** [twineworks/ruby-for-pentaho-kettle#20]
Hi All,

I have the Plugin working with the Java API - but the Ruby steps don't seem to be releasing memory for long running processes (I bind to a RabbitMQ queue and process). If I do the same thing with Java - the memory gets collected.

I think it may have something to do with logging from looking at a heap dump, but I'm not sure. Anything come to mind that I might be doing wrong?

Thanks again for a great addition to Pentaho!

**Comment by slawo-ch** [comment]
updated to jruby 9.1.x
