### ISSUE TITLE
Error in Transformation having Ruby Step

### ISSUE THREAD

**Issue by ysom2005** [twineworks/ruby-for-pentaho-kettle#26]
I have build and deployed the Ruby step in pdis.
Next I have a transformation which uses openssl and bouncy_castle gems. 
Also verified that all the gems are present in the Ruby/gems/gems folder.Executed the below command > java -Djruby.gem.home=gems -jar lib/jruby-complete.jar -S gem list
Output:
**\* LOCAL GEMS ***

activesupport (4.2.1, 4.0.2)
akami (1.3.0, 1.2.0)
atomic (1.1.99 java, 1.1.14 java)
bouncy-castle-java (1.5.0147)
bson (3.0.2 java, 1.9.2 java)
builder (3.2.2)
bundler (1.6.3)
bundler-unload (1.0.2)
chronic (0.10.2)
executable-hooks (1.3.2)
gem-wrappers (1.2.4)
gyoku (1.1.0, 1.0.0)
hoe (3.13.1, 3.7.2)
httpclient (2.6.0.1, 2.3.4.1)
httpi (2.1.0, 2.0.2)
i18n (0.7.0, 0.6.9)
jruby-launcher (1.1.0 java)
jruby-openssl (0.9.7 java, 0.9.5 java, 0.9.4)
json (1.8.1 java, 1.5.0 java)
json-jruby (1.5.0 java)
mime-types (2.0)
mini_portile (0.5.2)
minitest (5.6.1, 4.7.5)
mongo (1.3.1)
multi_json (1.8.2)
nokogiri (1.6.0 java)
nori (2.3.0, 2.1.0)
rack (1.5.2)
rake (10.4.2, 10.1.0, 10.0.3)
rest-client (1.6.7)
rubygems-bundler (1.4.4)
rubyntlm (0.3.4)
rvm (1.11.3.8)
savon (2.2.0, 0.9.2)
sources (0.0.1)
thread_safe (0.3.5 java, 0.1.3 java)
tzinfo (1.2.2, 0.3.38)
uuidtools (2.1.5, 2.1.4)
wasabi (3.1.0)

***********************************_Pentaho Transformation Run Error**_*************************************

Error :+1:    (root) at jar:file:/opt/pdis-5_2/plugins/steps/Ruby/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/custom_require.rb:1
  require at jar:file:/opt/pdis-5_2/plugins/steps/Ruby/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/custom_require.rb:60
   (root) at /data/pdis_repo/lib/api_helper.rb:1
org.pentaho.di.core.exception.KettleException: 
org.jruby.embed.EvalFailedException: org.jruby.embed.EvalFailedException: (LoadError) load error: openssl -- java.lang.NoClassDefFoundError: Could not initialize class org.jruby.ext.openssl.ASN1
org.jruby.embed.EvalFailedException: (LoadError) load error: openssl -- java.lang.NoClassDefFoundError: Could not initialize class org.jruby.ext.openssl.ASN1

```
at org.typeexit.kettle.plugin.steps.ruby.execmodels.SimpleExecutionModel.onProcessRow(SimpleExecutionModel.java:529)
```

**Comment by slawo-ch** [comment]
JRuby 9.1.13.x should have fixed the issue.
